# Generated by Django 4.0.3 on 2022-03-14 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 12, 45, 3, 280276, tzinfo=utc))),
                ('modificated', models.BooleanField(blank=True, default=False)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mc_tasklist.subject')),
            ],
        ),
    ]
